name: test

on:
  push:
    branches: [main, master]

jobs:
  test:
    defaults:
      run:
        working-directory: circuits
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.2
      with:
        toolchain: 0.7.1

    - name: Run tests
      run: |
        nargo test